In [1]:
import numpy as np 
from astropy.io import fits
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib ipympl

In [2]:
digal = np.loadtxt('../odata/CLAUDS_HSC_iband_igal')
digal0 = np.loadtxt('../odata/CLAUDS_HSC_iband_igal0')

In [5]:
dgal_properties = np.loadtxt('../gal_properties')

In [6]:
digal.shape, digal0.shape,dgal_properties.shape

((5607052, 6), (5607052, 8), (5607052, 16))

In [11]:
print(digal[2])
print('#')
print(digal0[-5])
print('#')
print(dgal_properties[-5])

[  3.     149.4327   2.879    1.7347  25.003  -19.7761]
#
[ 5.607048e+06  5.631447e+06  3.652520e+01 -3.759800e+00  2.897800e+00
  2.431800e+01 -2.181340e+01  4.627500e+00]
#
[ 5.607048e+06  3.652520e+01 -3.759800e+00  2.897800e+00 -9.900000e+01
  3.660000e-02  2.480400e+01  2.460100e+01  2.431800e+01  2.442700e+01
  2.463900e+01 -2.126600e+01 -2.137200e+01 -2.146000e+01  9.179200e+00
  2.199900e+00]


# Galaxy sample

In [33]:
'''
column 1: ra
column 2: dec
column 3: redshift
column 4: luminosity
column 5: i-band absolute magnitude
column 6: redshift error
'''
ngal = np.int64(np.arange(5607052)+1)
dgalaxy = np.vstack((ngal, digal[:,1],digal[:,2],digal[:,3],digal0[:,7],digal[:,5],dgal_properties[:,5])).T

In [26]:
dgalaxy.shape

(5607052, 6)

In [36]:
np.savetxt('/home/qyli/clu_finder/CLAUDS_HSC/catalogue/ReleaseSample/Galaxy', dgalaxy,
           fmt = '%-8d  %.4f  %.4f  %.4f  %.4f  %.4f  %.4f')

# Group sample

In [32]:
#This is identical with /home/qyli/clu_finder/CLAUDS_HSC/catalogue/odata/CLAUDS_HSC_iband_group

In [37]:
dgroup = np.loadtxt('../odata/CLAUDS_HSC_iband_group')

In [41]:
dfedge = np.loadtxt('../edges/CLAUDS_HSC_iband_grpfedge')

In [48]:
'''
column 1: group ID
column 2: richness
column 3: ra
column 4: dec
column 5: redshift
column 6: log M_h/(M_sun/h)
column 7: L_group (10^10Lsun/h/h) 
column 8: f_edge
'''

dgrp = np.append(dgroup, dfedge[:,1].reshape(dfedge.shape[0],1), axis = 1)

In [52]:
dgrp.shape

(2232134, 8)

In [58]:
np.savetxt('/home/qyli/clu_finder/CLAUDS_HSC/catalogue/ReleaseSample/Group', dgrp,
           fmt = '%-8d  %-5d  %8.4f  %8.4f  %8.4f  %8.4f  %8.4f  %5.3f')

In [50]:
dgroup[-1], dfedge[-1], dgrp[-1]

(array([ 2.232134e+06,  1.000000e+00,  3.634920e+01, -3.754300e+00,
         3.512500e+00,  1.175150e+01,  2.833800e+00]),
 array([2.232134e+06, 1.000000e+00]),
 array([ 2.232134e+06,  1.000000e+00,  3.634920e+01, -3.754300e+00,
         3.512500e+00,  1.175150e+01,  2.833800e+00,  1.000000e+00]))

# Member galaxies id

In [ ]:
#This is identical with /home/qyli/clu_finder/CLAUDS_HSC/catalogue/odata/iCLAUDS_HSC_iband_1, iCLAUDS_HSC_iband_2
'''
_1:
1. Ngal
2. belong to which group id
3. lum (1: brightest one; 2: not)
4. xM (1: most massive one; 2: not)

_2:
1. group id
2. galaxy id belong to this group
'''

# Protocluster candidates catalog